The AOVs from render layer nodes always connected to the Output File Node
ynput/ayon-blender pull request #82
Opened 2024-12-05 13:49 UTC by moonyuet

## Changelog Description
This PR is to make sure the AOVs from render layer nodes always connected to the Output File Node.
Resolve https://github.com/ynput/ayon-blender/issues/37

## Additional review information
n/a

## Testing notes:
1. Add some render settings in Ayon server
2. Create Render Instance with your camera
3. Publish

2024-12-05 15:01 UTC, LiborBatek requested changes
It does work when single ```Viewlayer``` present (render layer but in Blender terms)

the graph is correct when just one layer present>
![Screenshot 2024-12-05 155438](https://github.com/user-attachments/assets/21c1e078-8d7c-4f16-8bcc-b95c7a85bf5e)

but create ```Render``` fails and doesnt connect to file output node for the second ```Viewlayer``` as seen below (it fails and wrongly connects to file output node)...

![Screenshot 2024-12-05 155636](https://github.com/user-attachments/assets/1d49f5cf-0692-452a-86a7-e476c1125425)

2024-12-05 15:04 UTC, LiborBatek commented
Ideally it should be behaving like this mockup I created manually:

![Screenshot 2024-12-05 160404](https://github.com/user-attachments/assets/23f111a3-2d54-40df-9d07-deb7f807fed4)

2024-12-09 16:54 UTC, LiborBatek commented
@moonyuet it still does not work and to me it seems that it does not take the ```ViewLayer```s present into account at the collecting phase as it should propagate ```AOV```s set in the blender addon settings and turn those on automatically but this just happens on the default first ```ViewLayer``` and not any other present e.g, ```Layer2``` in my case...

Ideally we should first collect any ```ViewLayers```, then check if ```AOV```s set according to addons setting and lastly connect those to the ```file output``` node.

Im really not aware how much of this we already have in place (in terms of code) and which parts we miss completely atm...

2024-12-12 13:47 UTC, LiborBatek requested changes
Its getting better and better... now we have correct subpaths for each ```ViewLayer``` and also layer name included within ```filename``` which is good and desirable!

Now there are 2 more issues found:

1) When having set some ```AOV```s in the AYON addons settings, those are just propagated to the very first ```ViewLayer``` and not any other
![Screenshot 2024-12-12 143402](https://github.com/user-attachments/assets/409e4c6f-08b6-4c50-8cd6-3fb308c7ea1c)

2) when user does not create ```Scene node``` manually to introduce new additional ```ViewLayer.001``` in Composite tree,  AYON does not pick it up and just ignores the fact there is additional viewlayer(s) within the scene and uses just the default ```ViewLayer``` and use this for ```File Output``` node...




![Screenshot 2024-12-12 143332](https://github.com/user-attachments/assets/b2af7048-eec8-4b98-b81d-7470e56ed2e0)

So if setting all manually I am able to get the desired node tree with proper outputs for any ```ViewLayer``` present in the scene... like on the following scrn:

![image](https://github.com/user-attachments/assets/13c99afc-41e7-4391-a37e-07666174f49f)

And lastly (for consideration) is the limitation comming with the way we prepare ```AOVs``` via Addons settings...

as now if user have some AOVs turned on within his blender scene and triggers creation of ```Render``` instance it follows the addons settings so if no any matching AOVs present it will just remove any present AOVs - basically destroying all present AOV setups...


<img width="270" alt="Screenshot 2024-12-12 144611" src="https://github.com/user-attachments/assets/810c93c4-d1eb-4578-8814-5a20bbef47eb" />

2024-12-12 13:53 UTC, LiborBatek commented
So here is example when Ayon addons settings have ```empty AOVs``` fields (to create):

Before:

![Screenshot 2024-12-12 145003](https://github.com/user-attachments/assets/e54a86c6-afe0-4cb2-9e22-359d9be5e1d4)

After triggering ```Create``` > ```Render```

![Screenshot 2024-12-12 145025](https://github.com/user-attachments/assets/96d81fea-aa24-42a1-9421-87bdf442ee04)


We should probably think about approach that when no AOVs preconfigured, it wont force remove any existing ```AOV``` s during creation of ```Render``` instance... not destroying any user config within workfile.

2024-12-17 15:20 UTC, LiborBatek requested changes
So I have made another testing round with following findings:

1) no all AOVs got propagated from addons settings into blender once hitting create>Render
2) unfortunatelly it also removes any existing ```AOV```s during creation - big no no.

3) Blender freezes if more then one ```Scene``` node present when hitting create>Render instance (only when present tho see img below)

![Screenshot 2024-12-17 153002](https://github.com/user-attachments/assets/ed94e37c-6e5a-4fc3-8c2d-fea105c2dd1f)

if just single ```Scene node``` present and more than one ```ViewLayer``` present it doesnt freeze and sort of works...


![Screenshot 2024-12-17 153014](https://github.com/user-attachments/assets/24b8087d-0a6f-45b4-a6aa-b4643e75d46c)

there is a however issue that it multiplies even the already present ```Scene node``` which is not desirable as it mixes up connections to ```File Output``` node and results into duplicate outputs...
![B3d_RenderCreation](https://github.com/user-attachments/assets/fbb28db6-012e-4937-af6d-6b3a7869dbbd)

We should check if any ```Scene nodes``` already exists in the scene...to not create redundant ones...as seen here:
<img width="871" alt="Screenshot 2024-12-17 152847" src="https://github.com/user-attachments/assets/7d2f68f1-277f-48c9-a9e8-5410ab65a322" />

2024-12-18 14:07 UTC, LiborBatek reviewed
Now all works really well and been tested in different conditions...

single / multiple ```ViewLayers```, present / absent ```AOVs``` and full / empty AOVs preset in Addons Settings - seem all working nicely!

If any issue then there is one questionable thing regarding the ```Compositing``` aov...as there always exists just single node tree and output.

![Screenshot 2024-12-18 141257](https://github.com/user-attachments/assets/443d95b0-6ac8-4716-b63e-a95f8e8a4cb5)

Right now there is created input for ```composite``` for each ```ViewLayer``` which results into multiplied inputs and also empty ones (as only the first ```ViewLayer``` got connected)

We should introduce some logic and create/hook just the very first ```ViewLayer``` I guesss (it happens atm but there are also redundant other composite inputs which results into blank images and we shouldnt ideally create those at all)...cant think now if any occasion that might not be working with it...

2024-12-19 11:37 UTC, LiborBatek requested changes
After another testing round now there is just single ```Composite``` input into ```File Output``` node which is correct!

Also no any freeze of Blender happening if scene compositor pre occupied with multiple ```Scene``` nodes...also good!

There is only one flaw regarding the ```Composite``` AOV and that is created as an output for non default ```ViewLayer``` but for ```ViewLayer.001``` minor flaw but we should use that default viewLayer instead...

<img width="972" alt="Screenshot 2024-12-19 123203" src="https://github.com/user-attachments/assets/6abfcce1-93bb-4f9b-a383-af43e9b6c636" />


Other than that all good!

2024-12-23 10:10 UTC, LiborBatek requested changes
Now gives me following error after hit ```Create > Render```

```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\core_1.0.12+dev\ayon_core\pipeline\create\context.py", line 2126, in _create_with_unified_error
    result = creator.create(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.7+dev\ayon_blender\plugins\create\create_render.py", line 28, in create
    prepare_rendering(collection)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.7+dev\ayon_blender\api\render_lib.py", line 422, in prepare_rendering
    aov_file_product = set_node_tree(
                       ^^^^^^^^^^^^^^
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.7+dev\ayon_blender\api\render_lib.py", line 308, in set_node_tree
    output.base_path = render_product if multi_exr else str(output_path)
    ^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: CompositorNodeOutputFile.base_path expected a string type, not list
```

2024-12-30 10:51 UTC, LiborBatek requested changes
Now all seems correct and ```Render``` instance got created without any issues, also all inputs got connected into ```File Output``` node and only main aka default ```ViewLayer``` got outputted its ```Composite``` so all good on this front too..

![Screenshot 2024-12-30 112158](https://github.com/user-attachments/assets/0271b565-4afe-4a62-bd90-906096f83e3a)

there is one thing worth noting and that is ```Repair``` action for ```Output folder``` mess up the node tree and disconnects some inputs... probably not directly related but need to be resolved otherwise the setup will be broken as soon as triggering the repair action by user.

Resulting into following (note the File Output and disconnected inputs):


![Screenshot 2024-12-30 112726](https://github.com/user-attachments/assets/251b73e1-79bc-46e4-a4fb-1b71f1e7bdd5)

2025-01-03 13:49 UTC, LiborBatek requested changes
Now when hitting ```Repair``` action gives me following error:

```
Action: RepairAction (1d5c3061-3a67-43e2-b377-a6017efb328b)

Error: Action failed.

Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\core_1.0.12\ayon_core\pipeline\publish\publish_plugins.py", line 350, in process
    plugin.repair(instance)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.7+dev\ayon_blender\plugins\publish\validate_deadline_publish.py", line 103, in repair
    updated_render_product = update_render_product(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.7+dev\ayon_blender\api\render_lib.py", line 454, in update_render_product
    for rpass_name, render_pass in render_product.items():
                                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

```


![image](https://github.com/user-attachments/assets/a693d619-5168-4963-a55f-ea78157a2c66)

2025-01-06 16:23 UTC, LiborBatek requested changes
Now all node tree and its connections been maintained after clicking ```Repair``` action for output folder and setting correct version.

![image](https://github.com/user-attachments/assets/2cb08314-1719-4420-beaf-489ab54ed264)


However there is another error during publishing process:

![image](https://github.com/user-attachments/assets/e690ba72-892b-4f3d-b6ab-92b4347819fc)


```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\deadline_0.5.1\ayon_deadline\plugins\publish\global\submit_publish_job.py", line 377, in process
    instances = create_instances_for_aov(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\core_1.0.12\ayon_core\pipeline\farm\pyblish_functions.py", line 587, in create_instances_for_aov
    return _create_instances_for_aov(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\core_1.0.12\ayon_core\pipeline\farm\pyblish_functions.py", line 756, in _create_instances_for_aov
    collected_files = _collect_expected_files_for_aov(files)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\core_1.0.12\ayon_core\pipeline\farm\pyblish_functions.py", line 950, in _collect_expected_files_for_aov
    raise ValueError("Only one image sequence type is expected.")
ValueError: Only one image sequence type is expected.
```

2025-01-08 06:18 UTC, moonyuet commented
@LiborBatek I made lots of adjustments in regards. You need to re-create the render instances for publishing.

2025-01-08 08:41 UTC, LiborBatek commented
@moonyuet I will do another testing round but Im afraid that I have recreated the ```render``` instance each time...to have clean slate at the begining of the testing

just sayin :)

2025-01-08 12:36 UTC, LiborBatek commented
also worth mentioning that ```Repair``` action for output folder and version doesnt break anything (but shows error popup) but

```Repair``` action for output folder (the main one which usually been set to something like ```/tmp\``` doesnt produce the desired setup due to error showing up upon clicking the repair btn

2025-01-08 16:29 UTC, LiborBatek approved these changes
I think this issue is fully resolved as it works without glitches now...

also been tested with / without custom staging directory and works in both scenarios.

![Screenshot 2025-01-08 172013](https://github.com/user-attachments/assets/75073b5d-c3cd-4689-984f-5d59df67e1d0)

I would like to note a few things tho (probably not directly related to this PR tho),

first, the DL job doesnt respect batch frames (I have set it to 10 frames but on DL it is 1 frame for each) * this one is still relevant issue atm


~~second as we produce multiple frame sequences with ```_beauty``` naming there are issues in integration part aka with publish job on the farm (DL) ~~ not an issue anymore as it was succesfully tested on farm DL

Please bear those in mind, and let me know if these should also fall into this PR or are separate non relating issues we need to tackle! thx

2025-01-08 16:31 UTC, LiborBatek commented
Im mostly refering to scenarios with more than single ```ViewLayer```

in my case I had a 2 viewlayers ```Front``` and ```Bg``` ....so the reason for multiple beauty sequences later on when publishing job happen

2025-01-09 07:13 UTC, LiborBatek commented
Final check on Deadline Monitor proved everything properly finnished and also properly integrated in AYON.

All good!

2025-01-09 07:19 UTC, merged

2025-01-09 07:20 UTC, moonyuet commented
@BigRoy I merged this PR first so that you can work on your PR for further improving the render product type.