Version up current workfile in ayon menu
ynput/ayon-blender pull request #84
Opened 2024-12-11 08:36 UTC by moonyuet

## Changelog Description
This PR is to add version 
Resolve https://github.com/ynput/ayon-blender/issues/75

## Additional review information
n/a

## Testing notes:
1. Following the testing step in 75 to enable version up workfile
2. Launch Blender and `version up current workfile` would show up in the menu

2024-12-11 09:21 UTC, LiborBatek requested changes
It works in general (and perform incremental save) ...but there are few things to consider

First the menu item does have wrong tool tip as seen on the pic below:


![Screenshot 2024-12-11 101227](https://github.com/user-attachments/assets/c489a813-7fd7-4c3d-bcb1-0349630cedbc)

second I would follow the maya one by its naming and also put it as a first item in the AYON menu? I quite like that fact

![Screenshot 2024-12-11 101134](https://github.com/user-attachments/assets/1a41b22b-ee7f-4280-bd8f-1bd62f3efab4)

Lastly (optional) ```Blender``` natively offers ```Incremental Save``` via ```Ctrl+ALT+S``` and it would be cool to use it for AYON up version action too...so it would be as natural as anytime when in blender even without our integration... not sure tho if possible

2024-12-11 14:15 UTC, LiborBatek requested changes
Its better on top and with hotkey...which is cool but

![image](https://github.com/user-attachments/assets/9b4f6292-c47c-4183-9528-de5afbb8c91d)

Add correct name ```Version Up Workfile``` and Correct tooltip as now its off ```Launch Avalon Publisher```... to something like ```perform incremental save``` or so

2024-12-12 06:17 UTC, moonyuet commented on client/ayon_blender/api/ops.py
> +                    text="Version Up Current Workfile"
```suggestion
                    text="Version Up Workfile"
```

2024-12-12 08:58 UTC, LiborBatek approved these changes
Works like charm now!

![image](https://github.com/user-attachments/assets/b3722ebd-1edf-4722-b3fc-329483d0ac90)

2024-12-12 14:43 UTC, merged